### PR TITLE
Ban empty contracts, ban function blocks with mismatched declarations

### LINKED ISSUE #258: Function blocks accept clauses with different names
I don't think it should be legal. Also, makes my REPL unhappy.
```
contract C =
  entrypoint
    f() = 123
    g() = 123
```

### LINKED ISSUE #260: Compiler crashes on empty file
As I remember there is an attempt to handle this situation, but it seems to fail

### PR DESCRIPTION
**Pull request by radrow**
fixes #260 
fixes #258

### CODE REVIEW

File: src/aeso_ast_infer_types.erl [hunk 1]
```diff
@@ -626,7 +630,9 @@ infer_contract_top(Env, Kind, Defs0, _Options) ->
 %% a list of definitions.
 -spec infer_contract(env(), main_contract | contract | namespace, [aeso_syntax:decl()]) -> {env(), [aeso_syntax:decl()]}.
 infer_contract(Env0, What, Defs0) ->
+    create_type_errors(),
     Defs = process_blocks(Defs0),
+    destroy_and_report_type_errors(Env0),
```
Comment (radrow) [inline src/aeso_ast_infer_types.erl:635]: @UlfNorell could you verify? I could not leave these type errors undestroyed here because it was causing the whole compiler to crash, had to create separate ones for this particular case.

Comment (UlfNorell) [reply src/aeso_ast_infer_types.erl:635]: lgtm
